# Generated by Django 4.2.5 on 2023-10-04 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0004_versiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='versiculo',
            old_name='Versiculo',
            new_name='versiculo',
        ),
    ]
