# Generated by Django 4.2.5 on 2023-10-04 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0005_rename_versiculo_versiculo_versiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxs_lives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prox_live', models.DateTimeField()),
            ],
        ),
    ]
