# Generated by Django 4.2.5 on 2023-10-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0006_proxs_lives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxs_lives',
            old_name='prox_live',
            new_name='proxs_lives',
        ),
    ]
