# Generated by Django 4.2.5 on 2023-10-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0007_rename_prox_live_proxs_lives_proxs_lives'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxs_lives',
            old_name='proxs_lives',
            new_name='hora',
        ),
    ]
