# Generated by Django 4.2.5 on 2023-10-04 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0008_rename_proxs_lives_proxs_lives_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxs_lives',
            old_name='hora',
            new_name='proxs_lives',
        ),
    ]
