# Generated by Django 4.2.5 on 2023-10-05 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0009_rename_hora_proxs_lives_proxs_lives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiculo',
            name='versiculo',
            field=models.TextField(max_length=255),
        ),
    ]
