# Generated by Django 4.2.5 on 2023-10-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0010_alter_versiculo_versiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxs_lives',
            name='proxs_lives',
            field=models.TextField(max_length=255),
        ),
    ]
