# Generated by Django 4.2.5 on 2023-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0011_alter_proxs_lives_proxs_lives'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='assunto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventos',
            name='obs',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventos',
            name='pregador',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='data',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='proxs_lives',
            name='proxs_lives',
            field=models.CharField(max_length=255),
        ),
    ]
