# Generated by Django 4.2.5 on 2023-10-07 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0014_alter_eventos_assunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventos',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
