# Generated by Django 4.2.5 on 2023-10-08 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0015_eventos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
