# Generated by Django 4.2.5 on 2023-10-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ici', '0017_alter_eventos_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem_carosel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia_da_img', models.TextField(max_length=255)),
                ('img', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
